# Generated by Django 6.0 on 2025-12-21 09:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentsubmission',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='studentsubmission',
            name='is_processed',
        ),
        migrations.RemoveField(
            model_name='studentsubmission',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='studentsubmission',
            name='submission_date',
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentsubmission',
            name='course',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentsubmission',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
